const KEY='aieduMathSpiralProgressV1';
const AREAS=[
{id:'number',title:'수와 연산',icon:'🔢',color:'#2eb8ff',nodes:{'1-2':['20 이하의 수','수의 분해와 합성','10 만들기','한 자리 수 덧셈과 뺄셈','두 자리 수의 자릿값','두 자리 수 덧셈과 뺄셈'],'3-4':['큰 수','곱셈과 나눗셈','분수','소수','분수·소수의 덧셈과 뺄셈'],'5-6':['약수와 배수','어림','분수의 연산','소수의 연산','자연수 혼합 계산']}},
{id:'relation',title:'변화와 관계',icon:'🔁',color:'#8b7cf6',nodes:{'1-2':['반복 규칙','증가 규칙'],'3-4':['규칙을 수와 식으로','등호와 동치 관계'],'5-6':['대응 관계','비와 비율','비례식과 비례배분']}},
{id:'shape',title:'도형과 측정',icon:'📐',color:'#ff9b5c',nodes:{'1-2':['생활 속 모양','양의 비교','시각과 시간','cm와 m'],'3-4':['삼각형과 사각형','평면도형의 이동','각도','들이와 무게'],'5-6':['합동과 대칭','입체도형','둘레와 넓이','원의 넓이','겉넓이와 부피']}},
{id:'data',title:'자료와 가능성',icon:'📊',color:'#45c98c',nodes:{'1-2':['자료 분류','표와 간단한 그래프'],'3-4':['그림그래프','막대그래프','꺾은선그래프'],'5-6':['평균','띠그래프와 원그래프','가능성']}}
];
const STEPS=['경험하기','조작하기','시각화하기','기호화하기','설명하기','적용하기'];
let band='1-2',areaId='number',node='10 만들기',step=0,puzzle={filled:7,answer:3};
let progress=(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}})();
const key=(a,n)=>`${band}:${a}:${n}`;const completed=(a,n)=>!!progress[key(a,n)]?.completed;
function hideAll(){document.querySelectorAll('#main-container > .view-section').forEach(s=>{s.classList.add('hidden');s.style.display='none'})}
function show(id){hideAll();const s=document.getElementById(id);if(!s)return;s.classList.remove('hidden');s.style.display='flex';document.getElementById('aiedue-rpg-hud')?.classList.remove('hidden');document.body.classList.add('rpg-hud-active')}
const old={dashboard:window.openDashboard,activities:window.openMathActivities,time:window.openTimeQuiz};
window.openDashboard=()=>{document.querySelectorAll('.spiral-section').forEach(s=>{s.classList.add('hidden');s.style.display='none'});old.dashboard?.()};
window.openMathActivities=()=>{document.querySelectorAll('.spiral-section').forEach(s=>{s.classList.add('hidden');s.style.display='none'});old.activities?.()};
window.openTimeQuiz=()=>{document.querySelectorAll('.spiral-section').forEach(s=>{s.classList.add('hidden');s.style.display='none'});old.time?.()};
window.openSpiralCurriculum=()=>{show('spiral-map-section');renderMap()};
window.openSpiralLesson=(a,n)=>{areaId=a;node=n;step=0;show('spiral-lesson-section');renderLesson()};
function unlocked(a,i){return i===0||completed(a,AREAS.find(x=>x.id===a).nodes[band][i-1])}
function renderMap(){const h=document.getElementById('spiral-map-content');if(!h)return;const all=AREAS.flatMap(a=>a.nodes[band].map(n=>key(a.id,n)));const pct=Math.round(all.filter(k=>progress[k]?.completed).length/all.length*100)||0;h.innerHTML=`<div class="spiral-shell"><section class="spiral-hero"><div><p class="math-section-eyebrow">2022 개정 초등 수학</p><h1>나선형 배움 지도</h1><p>같은 핵심 개념을 다시 만나며 더 깊게 배워요.</p></div><div class="spiral-progress"><strong>전체 성장 ${pct}%</strong><div class="spiral-progress-track"><div class="spiral-progress-fill" style="width:${pct}%"></div></div></div></section><div class="spiral-tabs">${['1-2','3-4','5-6'].map(b=>`<button class="spiral-tab ${b===band?'active':''}" data-band="${b}">${b.replace('-','〜')}학년군</button>`).join('')}</div><section class="spiral-grid">${AREAS.map(a=>`<article class="spiral-area" style="--area:${a.color}"><h2>${a.icon} ${a.title}</h2><small>${a.nodes[band].length}개의 핵심 개념</small><div class="spiral-nodes">${a.nodes[band].map((n,i)=>{const d=completed(a.id,n),u=unlocked(a.id,i);return `<button class="spiral-node ${d?'completed':''} ${!u?'locked':''} ${u&&!d?'spiral-node-current':''}" data-area="${a.id}" data-node="${n}" ${!u?'disabled':''}>${d?'✓ ':u?'▶ ':'🔒 '}${n}</button>`}).join('')}</div></article>`).join('')}</section></div>`;h.querySelectorAll('[data-band]').forEach(b=>b.onclick=()=>{band=b.dataset.band;renderMap()});h.querySelectorAll('[data-node]').forEach(b=>b.onclick=()=>openSpiralLesson(b.dataset.area,b.dataset.node))}
function newPuzzle(){puzzle.filled=Math.floor(Math.random()*8)+1;puzzle.answer=10-puzzle.filled}
function renderLesson(){const h=document.getElementById('spiral-lesson-content');if(!h)return;const area=AREAS.find(a=>a.id===areaId),interactive=node==='10 만들기';if(interactive)newPuzzle();h.innerHTML=`<div class="spiral-shell"><section class="spiral-panel"><button class="spiral-action secondary" id="back-map">← 배움 지도</button><p class="math-section-eyebrow">${area.icon} ${area.title} · ${band.replace('-','〜')}학년군</p><h1 class="math-title">${node}</h1><div class="spiral-learning"><aside class="spiral-step-list">${STEPS.map((s,i)=>`<div class="spiral-step ${i===step?'active':''}">${i+1}. ${s}</div>`).join('')}</aside><main class="spiral-task">${interactive?tenTask():placeholder()}<p id="spiral-feedback" class="spiral-feedback" aria-live="polite"></p><div class="spiral-actions"><button class="spiral-action secondary" id="spiral-read">🔊 문제 읽기</button><button class="spiral-action secondary" id="spiral-hint">💡 힌트</button></div></main></div></section></div>`;document.getElementById('back-map').onclick=openSpiralCurriculum;document.getElementById('spiral-read').onclick=readTask;document.getElementById('spiral-hint').onclick=hint;h.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>check(Number(b.dataset.answer)));document.getElementById('complete-placeholder')?.addEventListener('click',completeStep)}
function tenTask(){const opts=[puzzle.answer,Math.max(0,puzzle.answer-1),Math.min(9,puzzle.answer+1)].filter((v,i,a)=>a.indexOf(v)===i).sort(()=>Math.random()-.5);return `<h2 class="text-2xl font-black text-center">10이 되려면 몇 개가 더 필요할까요?</h2><div class="ten-frame">${Array.from({length:10},(_,i)=>`<div class="ten-cell">${i<puzzle.filled?'<span class="ten-dot"></span>':''}</div>`).join('')}</div><p class="text-center text-xl font-black">${puzzle.filled} + □ = 10</p><div class="spiral-options">${opts.map(n=>`<button class="spiral-option" data-answer="${n}">${n}</button>`).join('')}</div>`}
function placeholder(){return `<div class="text-center"><div class="text-7xl mb-5">${AREAS.find(a=>a.id===areaId).icon}</div><h2 class="text-2xl font-black mb-3">${STEPS[step]} 활동</h2><p class="text-gray-500 font-bold mb-6">이 개념의 공통 학습 흐름을 확인하는 시범 화면입니다.</p><button id="complete-placeholder" class="spiral-action">이 단계 완료</button></div>`}
function check(v){const f=document.getElementById('spiral-feedback');if(v!==puzzle.answer){f.textContent='아직 10이 되지 않아요. 빈칸을 하나씩 세어 보세요.';f.className='spiral-feedback bad';return}f.textContent='정답이에요! 다음 표현 단계로 이동합니다.';f.className='spiral-feedback good';setTimeout(completeStep,650)}
function completeStep(){if(step<STEPS.length-1){step++;renderLesson();return}progress[key(areaId,node)]={completed:true,completedAt:new Date().toISOString()};localStorage.setItem(KEY,JSON.stringify(progress));window.showModal?.(`<strong>${node}</strong> 배움을 완료했어요!<br>다음 개념이 열렸습니다.`);openSpiralCurriculum()}
function hint(){const f=document.getElementById('spiral-feedback');f.textContent=node==='10 만들기'?'빈칸의 개수를 세면 10에 더 필요한 수를 찾을 수 있어요.':'그림이나 구체물로 먼저 나타내 보세요.';f.className='spiral-feedback'}
function readTask(){const t=node==='10 만들기'?`${puzzle.filled}에 얼마를 더하면 10이 될까요?`:`${node}, ${STEPS[step]} 활동입니다.`;speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}
function enhance(){const board=document.querySelector('#dashboard-section .math-stage-board');if(!board||document.getElementById('spiral-dashboard-card'))return;const c=document.createElement('button');c.type='button';c.id='spiral-dashboard-card';c.className='dashboard-stage-card level-card';c.innerHTML='<span class="stage-badge">CURRICULUM</span><span class="stage-emoji" aria-hidden="true">🌀</span><span class="level-title">나선형 배움</span><span class="level-desc">초등 1〜6학년</span><span class="stage-note">4개 영역 · 학년군별 핵심 개념 지도</span>';c.onclick=openSpiralCurriculum;const locked=board.querySelector('.locked');locked?locked.replaceWith(c):board.append(c)}
document.addEventListener('DOMContentLoaded',()=>{enhance();renderMap()});