import {useState} from 'react';
import {Edit3,Save} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Choice,Field,PrintButton,RemoveButton,StudentChoice,useClassroom} from './shared';
import {today} from '@/lib/types';

export default function Timetable(){
    const {entries,students,selectedStudent,setSelectedStudent,save,busy}=useClassroom();
    const [weekday,setWeekday]=useState('월'),[period,setPeriod]=useState('1'),[subject,setSubject]=useState(''),[room,setRoom]=useState('우리 반'),[support,setSupport]=useState('');
    const studentName=students.find(s=>s.id===selectedStudent)?.payload.name||'';
    const schedule=entries.filter(e=>e.kind==='schedule'&&(!selectedStudent||e.studentId===selectedStudent));
    return <div className="management-grid"><section className="panel no-print"><h2 className="panel-title">수업 배치</h2><StudentChoice optional={false}/><div className="field-pair"><Choice label="요일" value={weekday} onChange={setWeekday} options={Array.from("월화수목금").map(v=>({id:v,label:v+"요일"}))}/><Choice label="교시" value={period} onChange={setPeriod} options={Array.from({length:6},(_,i)=>({id:String(i+1),label:i+1+"교시"}))}/></div><Field label="과목·활동" value={subject} onChange={e=>setSubject(e.target.value)} placeholder="예: 국어 / 급식 지원"/><Field label="장소" value={room} onChange={e=>setRoom(e.target.value)}/><Field label="지원 인력" value={support} onChange={e=>setSupport(e.target.value)} placeholder="선택 사항"/><Button disabled={busy||!selectedStudent||!subject.trim()} onClick={async()=>{try{const previous=schedule.find(e=>e.studentId===selectedStudent&&e.payload.weekday===weekday&&e.payload.period===period);await save("schedule",{studentName,weekday,period,subject,room,support},selectedStudent,today(),previous?.id)}catch{}}}><Save size={16}/>시간표 저장</Button></section><section className="panel timetable-panel"><div className="section-heading"><h2>{studentName||"전체 학생"} 시간표</h2><div className="no-print"><PrintButton/></div></div><Table className="timetable"><TableHeader><TableRow><TableHead>교시</TableHead>{Array.from("월화수목금").map(d=><TableHead key={d}>{d}</TableHead>)}</TableRow></TableHeader><TableBody>{Array.from({length:6},(_,i)=><TableRow key={i}><TableCell>{i+1}</TableCell>{Array.from("월화수목금").map(d=><TableCell key={d}>{schedule.filter(e=>e.payload.weekday===d&&e.payload.period===String(i+1)).map(e=><div className="lesson" key={e.id}><strong>{e.payload.subject}</strong>{!selectedStudent&&<small>{e.payload.studentName}</small>}<small>{e.payload.room}{e.payload.support&&" · "+e.payload.support}</small><div className="no-print lesson-actions"><Button variant="ghost" aria-label="수업 수정" onClick={()=>{setSelectedStudent(e.studentId);setWeekday(d);setPeriod(String(i+1));setSubject(e.payload.subject);setRoom(e.payload.room);setSupport(e.payload.support||"")}}><Edit3 size={13}/></Button><RemoveButton entry={e}/></div></div>)}</TableCell>)}</TableRow>)}</TableBody></Table></section></div>;
}
