"use client";
import {useEffect,useRef,useState} from "react";
import {Check,Eye,FileText,RefreshCw,Save} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Switch} from "@/components/ui/switch";
import {Textarea} from "@/components/ui/textarea";
import {toast} from "@/lib/notify";
import {Choice,Empty,Field,PrintButton,RemoveButton,StudentChoice,useClassroom} from "./shared";
import {defaultSettings,generate,koreanCategories,mathCategories,Problem,Settings,types} from "@/lib/generator";
import {today} from "@/lib/types";
import reading from "@/data/reading-content.json";
import data from "@/data/classroom-data.json";
type Sheet={studentId?:string;settings:Settings;problems:Problem[];title:string;studentName:string;date:string;passage?:any};
function initial(){let seed=49;const rng=()=>{seed=(seed*16807)%2147483647;return seed/2147483647};return {settings:defaultSettings,problems:generate(defaultSettings,rng),title:"음절·낱말 읽기",studentName:"",date:""} as Sheet}
function clockPoint(degrees:number,radius:number){return {x:75+Math.sin(degrees*Math.PI/180)*radius,y:75-Math.cos(degrees*Math.PI/180)*radius}}
function Clock({hour,minute}:{hour:number;minute:number}){const h=clockPoint(hour*30+minute*.5,31),m=clockPoint(minute*6,46);return <svg viewBox="0 0 150 150" className="learning-clock" role="img" aria-label="시침과 분침을 보고 시간을 읽어 보세요"><circle cx="75" cy="75" r="69" fill="white" stroke="#667da5" strokeWidth="2"/>{Array.from({length:12},(_,i)=>{const p=clockPoint((i+1)*30,55);return <text key={i} x={p.x} y={p.y+4} textAnchor="middle" fontSize="12" fill="#304766">{i+1}</text>})}<line x1="75" y1="75" x2={h.x} y2={h.y} stroke="#253f70" strokeWidth="5" strokeLinecap="round"/><line x1="75" y1="75" x2={m.x} y2={m.y} stroke="#6585c7" strokeWidth="3" strokeLinecap="round"/><circle cx="75" cy="75" r="4" fill="#253f70"/></svg>}
function decompose(t:string){const initials="ㄱㄲㄴㄷㄸㄹㅁㅂㅃㅅㅆㅇㅈㅉㅊㅋㅌㅍㅎ",medials="ㅏㅐㅑㅒㅓㅔㅕㅖㅗㅘㅙㅚㅛㅜㅝㅞㅟㅠㅡㅢㅣ",finals=["","ㄱ","ㄲ","ㄳ","ㄴ","ㄵ","ㄶ","ㄷ","ㄹ","ㄺ","ㄻ","ㄼ","ㄽ","ㄾ","ㄿ","ㅀ","ㅁ","ㅂ","ㅄ","ㅅ","ㅆ","ㅇ","ㅈ","ㅊ","ㅋ","ㅌ","ㅍ","ㅎ"];return Array.from(t).map(c=>{const n=c.codePointAt(0)!-0xAC00;return n>=0&&n<11172?[initials[Math.floor(n/588)],medials[Math.floor(n%588/28)],finals[n%28]].filter(Boolean).join(" "):c}).join(" / ")}
export default function Worksheet(){const {students,selectedStudent,setSelectedStudent,entries,save,busy}=useClassroom();const [config,setConfig]=useState<Settings>(defaultSettings),[sheet,setSheet]=useState<Sheet>(initial),[date,setDate]=useState(today),[name,setName]=useState(""),[answers,setAnswers]=useState(false),[passageId,setPassageId]=useState("ants"),[writingId,setWritingId]=useState("poem");const actionRef=useRef<any>(null);const selected=students.find(s=>s.id===selectedStudent);
const set=(key:keyof Settings,value:any)=>setConfig(s=>({...s,[key]:value}));
function build(settings=config){try{let problems:Problem[],passage:any,title=types[settings.subject]?.find(t=>t.id===settings.type)?.label||"학습지";
if(settings.type==="reading"){passage=reading.passages.find(p=>p.id===passageId)||reading.passages[0];title=passage.title;problems=passage.questions.map((text:string)=>({text,kind:"reading"}))}
else if(settings.type==="writing"){const task=data.blankWorksheets.tasks.find(t=>t.id===writingId)!;title=task.title;problems=[{text:settings.custom||task.instructions.join("\n")||"내 생각을 자유롭게 써 보세요.",kind:"writing"}]}
else{problems=generate(settings);if(settings.type==="word")title=mathCategories.find(c=>c.id===settings.bank)?.label||title;if(settings.type==="syllables")title=koreanCategories.find(c=>c.id===settings.bank)?.label||title}
if(settings.type==="intro"&&selected){const p=selected.payload,values=[p.name,p.school,[p.grade&&p.grade+"학년",p.classRoom&&p.classRoom+"반"].filter(Boolean).join(" "),p.address,p.phone,p.favorite,"",p.dream,""];problems=problems.map((q,i)=>({...q,answer:values[i]||""}))}
const result={studentId:selectedStudent,settings:{...settings},problems,title,studentName:selected?.payload.name||name,date,passage};setSheet(result);setAnswers(false);return result}catch(e:any){toast.error(e.message);throw e}}
actionRef.current={build,config,sheet,setConfig};
useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const life=new AbortController();Promise.resolve(ctx.registerTool({name:"generate_math_worksheet",title:"수학 학습지 만들기",description:"현재 화면에 수학 학습지를 새로 생성합니다. 저장하거나 인쇄하지 않습니다.",inputSchema:{type:"object",properties:{type:{type:"string",enum:["add","subtract","multiply","divide","number","fractions","decimal","time"]},level:{type:"integer",minimum:1,maximum:3},count:{type:"integer",minimum:1,maximum:30}},required:["type","level","count"],additionalProperties:false},annotations:{readOnlyHint:false},async execute(input:any){if(!input||!["add","subtract","multiply","divide","number","fractions","decimal","time"].includes(input.type)||!Number.isInteger(input.level)||input.level<1||input.level>3||!Number.isInteger(input.count)||input.count<1||input.count>30)throw Error("학습지 설정을 확인해 주세요.");const next={...defaultSettings,...input,subject:"math"};actionRef.current.setConfig(next);const result=actionRef.current.build(next);await new Promise(requestAnimationFrame);return {title:result.title,count:result.problems.length}}},{signal:life.signal})).catch(()=>{});Promise.resolve(ctx.registerTool({name:"read_current_worksheet",title:"현재 학습지 읽기",description:"화면에 생성된 학습지의 제목과 문항을 읽습니다.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(){const s=actionRef.current.sheet;return {title:s.title,count:s.problems.length,problems:s.problems}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
const fixed=["hangul","double","batchim","alphabet","reading","writing","copy","request","intro","measure"].includes(config.type);
const saved=entries.filter(e=>e.kind==="worksheet"&&(!selectedStudent||e.studentId===selectedStudent));
let perPage=sheet.settings.type==="alphabet"?13:sheet.problems[0]?.kind==="hangul"?14:sheet.passage?3:sheet.settings.type==="word"?4:sheet.problems[0]?.kind==="writing"?1:sheet.problems[0]?.kind==="clock"?6:["copy","intro","dictation"].includes(sheet.problems[0]?.kind||"")?8:10;
const pages=Array.from({length:Math.max(1,Math.ceil(sheet.problems.length/perPage))},(_,i)=>sheet.problems.slice(i*perPage,(i+1)*perPage));
return <><div className="studio"><section className="control-panel"><h2><span className="step">1</span>학습지 설정</h2><StudentChoice/>{!selectedStudent&&<Field label="이름 직접 입력" placeholder="선택 사항" value={name} onChange={e=>setName(e.target.value)}/>}<Field label="날짜" type="date" value={date} onChange={e=>setDate(e.target.value)}/><Choice label="과목" value={config.subject} options={[{id:"math",label:"수학"},{id:"korean",label:"국어"},{id:"english",label:"영어"},{id:"life",label:"생활 학습"}]} onChange={v=>setConfig({...defaultSettings,subject:v,type:types[v][0].id,bank:v==="korean"?"no-batchim-2":"word-01"})}/><Choice label="학습 유형" value={config.type} options={types[config.subject]} onChange={v=>set("type",v)}/>
{config.type==="word"&&<Choice label="문제은행" value={config.bank} onChange={v=>set("bank",v)} options={mathCategories.map(c=>({id:c.id,label:c.label}))}/>}
{config.type==="syllables"&&<Choice label="읽기 수준" value={koreanCategories.some(c=>c.id===config.bank)?config.bank:"no-batchim-2"} onChange={v=>set("bank",v)} options={koreanCategories.map(c=>({id:c.id,label:c.label}))}/>}
{config.type==="reading"&&<Choice label="읽을 글" value={passageId} onChange={setPassageId} options={reading.passages.map(c=>({id:c.id,label:c.title+(c.level==="고학년"?" · 고학년":"")}))}/>}
{config.type==="writing"&&<Choice label="글쓰기 활동" value={writingId} onChange={setWritingId} options={data.blankWorksheets.tasks.map(c=>({id:c.id,label:c.title}))}/>}
{["add","subtract","multiply","divide","number","time"].includes(config.type)&&<Choice label={config.type==="time"?"시간 단위":"수의 수준"} value={String(config.level)} onChange={v=>set("level",+v)} options={config.type==="time"?[{id:"1",label:"정각·30분"},{id:"2",label:"1분 단위"}]:[{id:"1",label:"한 자리 수"},{id:"2",label:"두 자리 수"},{id:"3",label:"세 자리 수"},...(config.type==="number"?[{id:"4",label:"만·억 단위"}]:[])]}/>}
{["add","subtract"].includes(config.type)&&<Choice label={config.type==="add"?"받아올림":"받아내림"} value={config.carry} onChange={v=>set("carry",v)} options={[{id:"any",label:"제한 없음"},{id:"no",label:"없음"},{id:"yes",label:"있음"}]}/>}
{config.type==="multiply"&&<Choice label="구구단 지정" value={String(config.table)} onChange={v=>set("table",+v)} options={[{id:"0",label:"지정하지 않음"},...Array.from({length:8},(_,i)=>({id:String(i+2),label:i+2+"단"}))]}/>}
{config.type==="batchim"&&<Choice label="받침" value={String(config.table)} onChange={v=>set("table",+v)} options={Array.from("ㄱㄴㄷㄹㅁㅂㅅㅇㅈㅊㅋㅌㅍㅎ").map((v,i)=>({id:String(i),label:v}))}/>}
{["divide","fractions"].includes(config.type)&&<div className="switch-field"><label htmlFor="remainder">{config.type==="divide"?"나머지 있는 문제":"가분수도 포함"}</label><Switch id="remainder" checked={config.remainder} onCheckedChange={v=>set("remainder",v)}/></div>}
{config.type==="decimal"&&<Choice label="연산" value={config.carry} onChange={v=>set("carry",v)} options={[{id:"any",label:"덧셈"},{id:"no",label:"뺄셈"}]}/>}
{["copy","writing","request"].includes(config.type)&&<div className="field"><label htmlFor="customText">{config.type==="copy"?"연습할 단어·문장":"활동 안내"}</label><Textarea id="customText" rows={4} value={config.custom||""} onChange={e=>set("custom",e.target.value)} placeholder={config.type==="copy"?"한 줄에 하나씩 입력하세요.":"선택 사항"}/></div>}
{!fixed&&<Choice label="문항 수" value={String(config.count)} onChange={v=>set("count",+v)} options={[5,6,8,10,15,20,28,30].map(n=>({id:String(n),label:n+"문항"}))}/>}
{["add","subtract","multiply"].includes(config.type)&&<Choice label="문제 배치" value={config.layout} onChange={v=>set("layout",v)} options={[{id:"horizontal",label:"가로식"},{id:"vertical",label:"세로식"}]}/>}
<Button className="generate-btn" onClick={()=>{try{build()}catch{}}}><RefreshCw size={17}/>새 문제 만들기</Button><div className="tip"><strong>{config.type==="word"?"문제은행에서 중복 없이":config.type==="syllables"?"음절을 또박또박":"필요한 만큼 반복 연습"}</strong><p>{config.type==="syllables"?"의미 없는 음절 조합도 포함된 읽기 연습 자료예요.":"설정을 바꾼 뒤 새 문제 만들기를 누르세요."}</p></div></section>
<section className="preview-panel"><div className="preview-toolbar"><div><span className="live-dot"/>미리보기 <span className="muted">{pages.length}장</span></div><div>{sheet.problems.some(p=>p.answer)&&<label className="inline-switch"><Switch checked={answers} onCheckedChange={setAnswers}/>정답·예시</label>}<Button variant="outline" disabled={busy} onClick={async()=>{try{await save("worksheet",{...sheet,date:sheet.date||date},sheet.studentId||"",sheet.date||date)}catch{}}}><Save size={15}/>저장</Button><PrintButton/></div></div>
{pages.map((page,pageIdx)=><article className={"paper "+(page[0]?.kind==="hangul"?"hangul-paper":"")} key={pageIdx}><div className="paper-top"><span>에이두 한글 · {({math:"수학",korean:"국어",english:"영어",life:"생활 학습"} as any)[sheet.settings.subject]}</span><span>{pageIdx+1} / {pages.length}</span></div><h2>{sheet.title}</h2><div className="paper-meta"><span>날짜　{sheet.date||date}</span><span>이름　{sheet.studentName||"________________"}</span></div><p className="paper-instruction">{sheet.settings.type==="fractions"?"분수를 읽고 진분수와 가분수를 구별해 보세요.":sheet.settings.type==="money"?"만원권과 천원권의 장수를 세고 모두 얼마인지 써 보세요.":sheet.settings.type==="time"?"시침과 분침을 보고 시간을 써 보세요.":sheet.settings.subject==="korean"?"천천히 읽고, 또박또박 써 보세요.":"빈칸에 알맞은 답을 써 보세요."}</p>
{sheet.passage&&<div className="reading-passage"><p>{sheet.passage.text}</p></div>}
<div className={"question-grid "+(["word","reading","writing","hangul","intro"].includes(page[0]?.kind||"")?"single-column":"")}>{page.map((q,i)=><div className={"question question-"+q.kind} key={i}><span className="q-number">{String(pageIdx*perPage+i+1).padStart(2,"0")}</span>
{q.kind==="equation"?<div className={"equation "+(sheet.settings.layout==="vertical"?"vertical-equation":"")}>{sheet.settings.layout==="vertical"?<><div>{q.a}</div><div>{q.op} {q.b}</div><div className="vertical-answer">{answers?q.answer:"　"}</div></>:<>{q.a} {q.op} {q.b} = <span className={"answer-box "+(answers?"filled":"")}>{answers?q.answer:""}</span></>}</div>
:q.kind==="clock"?<div className="clock-problem"><Clock hour={q.a!} minute={q.b!}/><p>{answers?q.answer:"_____시 _____분"}</p></div>
:q.kind==="money"?<><div className="money-count"><span>만원권 <b>{q.a}</b>장</span><span>천원권 <b>{q.b}</b>장</span></div><div className="ruled-answer">{answers?q.answer:"모두 _______________원"}</div></>
:q.kind==="fraction"?<div className="fraction-problem"><span className="fraction"><b>{q.a}</b><b>{q.b}</b></span><span>{answers?q.answer:"( 진분수 / 가분수 )"}</span></div>
:q.kind==="number"?<><div className="number-read">{q.text}</div><div className="ruled-answer">{answers?q.answer:""}</div></>
:q.kind==="copy"?<><div className="copy-word">{q.text}</div><div className="copy-line"><span>{q.text}</span><span>　</span></div>{sheet.settings.type==="request"&&<p className="decomposition">{decompose(q.text)}</p>}</>
:q.kind==="hangul"?<div className="hangul-row">{q.text.split(" ").map((c,j)=><span key={j}>{c}</span>)}</div>
:q.kind==="intro"?<><strong className="intro-prompt">{q.text}</strong><div className="ruled-answer">{answers?q.answer:""}</div></>
:q.kind==="writing"?<><p>{q.text}</p><div className="writing-lines">{Array.from({length:13},(_,j)=><div key={j}/>)}</div><div className="guardian">보호자 한줄 평가 ________________________<br/>보호자 서명 ________________________</div></>
:<><p className="word-question">{q.text}</p><div className="ruled-answer">{q.kind==="word"?"답:":""}</div></>}
</div>)}</div><div className="paper-bottom"><span>끝까지 해낸 나에게 칭찬 한마디</span><span>참 잘했어요!</span></div></article>)}</section></div>
<section className="panel saved-sheets no-print"><div className="section-heading"><h2>저장한 학습지</h2><span className="muted">{saved.length}개</span></div>{saved.length?<div className="saved-list">{saved.map(e=><div key={e.id} className="saved-row"><FileText size={19}/><div><strong>{e.payload.title}</strong><small>{e.date} · {e.payload.studentName||"공통 학습지"} · {e.payload.problems?.length||0}문항</small></div><Button variant="outline" onClick={()=>{setSheet(e.payload as Sheet);setConfig(e.payload.settings);setSelectedStudent(e.studentId);setAnswers(false);window.scrollTo({top:0,behavior:"smooth"})}}>불러오기</Button><RemoveButton entry={e}/></div>)}</div>:<Empty title="다시 쓸 학습지를 저장해 보세요">생성한 문제를 그대로 보관하고 나중에 다시 인쇄할 수 있어요.</Empty>}</section></>}
