import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {novetusReference} from './novetus.mjs';
const hex=/^#[0-9a-f]{6}$/i;const kinds=new Set(['box','ball','cylinder','wedge','spawn']);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
function vec(v,min,max){if(!Array.isArray(v)||v.length!==3||v.some(n=>typeof n!=='number'||!Number.isFinite(n)||n<min||n>max))throw Error('좌표·크기가 범위를 벗어났습니다.');return [...v];}
export function normalizeScene(input){
 if(!input||typeof input!=='object'||!Array.isArray(input.objects)||!input.objects.length||input.objects.length>800)throw Error('맵은 1~800개 부품으로 구성해야 합니다.');
 const title=String(input.title||'내가 만든 맵').trim();if(!title||title.length>60)throw Error('맵 이름은 1~60자입니다.');
 const ids=new Set();const objects=input.objects.map((o,i)=>{
  if(!kinds.has(o.kind)||!hex.test(o.color||''))throw Error('지원하지 않는 부품·색상입니다.');
  const id=String(o.id||'part-'+i);if(!/^[a-zA-Z0-9_-]{1,40}$/.test(id)||ids.has(id))throw Error('부품 ID가 잘못됐습니다.');ids.add(id);
  const obj={id,kind:o.kind,position:vec(o.position,-512,512),size:vec(o.size,0.2,256),rotation:vec(o.rotation||[0,0,0],-360,360),color:o.color.toLowerCase()};
  if(o.texture){const a=novetusReference(o.texture,'image');if(!['1900000001','1900000002','1900000003'].includes(o.texture)&&!a)throw Error('등록되지 않은 이미지 에셋입니다.');obj.texture=a?.key||o.texture;}
  if(o.mesh){const a=novetusReference(o.mesh.asset,'mesh');if(!a)throw Error('등록되지 않은 메시입니다.');obj.mesh={asset:a.key,scale:vec(o.mesh.scale||[1,1,1],0.001,256),offset:vec(o.mesh.offset||[0,0,0],-256,256)};if(o.mesh.texture){const t=novetusReference(o.mesh.texture,'image');if(!t)throw Error('등록되지 않은 메시 텍스처입니다.');obj.mesh.texture=t.key;}}
  return obj;
 });
 if(!objects.some(o=>o.kind==='spawn'))throw Error('시작 지점을 하나 이상 배치해 주세요.');if(objects.filter(o=>o.kind==='spawn').length>8)throw Error('시작 지점은 최대 8개입니다.');
 const result={version:1,title,objects};if(input.provenance){const p=input.provenance,a=novetusReference(p.key);if(a)result.provenance={key:a.key,repo:a.repo,path:a.path,revision:a.revision,notice:'원본 지형·에셋 변환. 스크립트 제외.'};}return result;
}
function prop(t,n,s){return `<${t} name="${n}">${s}</${t}>`;}
const vector=(n,v)=>prop('Vector3',n,`<X>${v[0]}</X><Y>${v[1]}</Y><Z>${v[2]}</Z>`);
function frame(o){const [x,y,z]=o.rotation.map(a=>a*Math.PI/180),a=Math.cos(x),b=Math.sin(x),c=Math.cos(y),d=Math.sin(y),e=Math.cos(z),f=Math.sin(z);const r=[c*e,-c*f,d,a*f+b*d*e,a*e-b*d*f,-b*c,b*f-a*d*e,b*e+a*d*f,a*c];return prop('CoordinateFrame','CFrame',o.position.map((v,i)=>`<${'XYZ'[i]}>${v}</${'XYZ'[i]}>`).join('')+r.map((v,i)=>`<R${Math.floor(i/3)}${i%3}>${v}</R${Math.floor(i/3)}${i%3}>`).join(''));}
export function compileScene(scene,id,root){const bodies=scene.objects.map(o=>{const cls=o.kind==='spawn'?'SpawnLocation':o.kind==='wedge'?'WedgePart':'Part',rgb=parseInt(o.color.slice(1),16);return `<Item class="${cls}" referent="P_${o.id}"><Properties>${prop('string','Name',esc(o.kind==='spawn'?'CreatorSpawn':o.id))}${prop('bool','Anchored','true')}${prop('bool','CanCollide','true')}${prop('token','formFactorRaw','3')}${vector('size',o.size)}${frame(o)}${prop('Color3uint8','Color3uint8',rgb)}${prop('token','TopSurface','0')}${prop('token','BottomSurface','0')}${cls==='Part'?prop('token','shape',o.kind==='ball'?0:o.kind==='cylinder'?2:1):''}${cls==='SpawnLocation'?prop('bool','Neutral','true')+prop('float','Duration','3'):''}</Properties>${o.texture?`<Item class="Decal" referent="D_${o.id}"><Properties>${prop('string','Name','CreatorTexture')}${prop('token','Face','5')}${prop('Content','Texture',`<url>rbxassetid://${novetusReference(o.texture)?.id||o.texture}</url>`)}</Properties></Item>`:''}${o.mesh?`<Item class="SpecialMesh" referent="M_${o.id}"><Properties>${prop('string','Name','NovetusMesh')}${prop('token','MeshType','5')}${prop('Content','MeshId',`<url>rbxassetid://${novetusReference(o.mesh.asset).id}</url>`)}${o.mesh.texture?prop('Content','TextureId',`<url>rbxassetid://${novetusReference(o.mesh.texture).id}</url>`):''}${vector('Scale',o.mesh.scale)}${vector('Offset',o.mesh.offset)}</Properties></Item>`:''}</Item>`;}).join('');const scripts=['avatar-colors.lua','character-motion.lua','character-look.lua'];const color=fs.readFileSync(path.join(root,'maps',scripts[0]),'utf8');const telemetry=`${color}\nprint('ROBL_MAP_READY ${id}')\nlocal players=game:GetService('Players')\nlocal function attach(p) print('ROBL_PLAYER_JOIN '..p.Name);p.CharacterAdded:connect(function(c) wait(1);applyAiedueAvatar(p,c);local t=c:FindFirstChild('Torso');if t then print('ROBL_CHARACTER '..p.Name..' torso='..tostring(t.Color)) end end)end\nplayers.PlayerAdded:connect(attach);for _,p in pairs(players:GetPlayers()) do attach(p) end\nwhile wait(1) do for _,p in pairs(players:GetPlayers()) do local c=p.Character;local t=c and c:FindFirstChild('Torso');if t then print('ROBL_POS '..p.Name..' '..tostring(t.Position)) end end end`;
const source=(name,lua)=>`<Item class="Script" referent="S_${name}"><Properties>${prop('string','Name',name)}${prop('bool','Disabled','false')}${prop('ProtectedString','Source',esc(lua))}</Properties></Item>`;
return `<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="4"><External>null</External><External>nil</External><Item class="Workspace" referent="WORK"><Properties>${prop('string','Name','Workspace')}</Properties>${bodies}${source('CreatorTelemetry',telemetry)}${source('CreatorMotion',fs.readFileSync(path.join(root,'maps',scripts[1]),'utf8'))}${source('CreatorLook',fs.readFileSync(path.join(root,'maps',scripts[2]),'utf8'))}</Item><Item class="HttpService" referent="HTTP"><Properties>${prop('string','Name','HttpService')}${prop('bool','HttpEnabled','true')}</Properties></Item><Item class="Lighting" referent="LIGHT"><Properties>${prop('string','Name','Lighting')}${prop('float','ClockTime','14')}${prop('Color3','Ambient','<R>0.5</R><G>0.5</G><B>0.5</B>')}</Properties></Item></roblox>`;}
export function createCreatorStore({dir,root}){const indexFile=dir&&path.join(dir,'index.json');const entries=indexFile&&fs.existsSync(indexFile)?JSON.parse(fs.readFileSync(indexFile,'utf8')):[];const checkId=id=>{if(!/^made-[a-f0-9]{16}$/.test(id))throw Error('알 수 없는 제작맵입니다.');return id;};const save=()=>{if(!dir)throw Error('제작맵 저장소가 준비되지 않았습니다.');fs.mkdirSync(dir,{recursive:true,mode:0o700});fs.writeFileSync(indexFile+'.tmp',JSON.stringify(entries),{mode:0o600});fs.renameSync(indexFile+'.tmp',indexFile);};const find=id=>entries.find(e=>e.id===id);
return {list(account){return entries.map(e=>({id:e.id,title:e.title,description:`${e.count}개 부품 · ${e.author} 제작`,source:'교사 제작',mode:'탐험',available:true,editable:account?.uid===e.owner}));},map(id){const e=find(id);return e?{id:e.id,title:e.title,file:path.join(dir,id+'.rbxlx'),path:path.join(dir,id+'.rbxlx')}:null;},read(account,id){const e=find(checkId(id));if(!e)throw Error('맵을 찾을 수 없습니다.');if(account.role!=='teacher'||e.owner!==account.uid){const err=Error('내가 만든 맵만 편집할 수 있습니다.');err.status=403;throw err;}return {id,revision:e.revision,scene:JSON.parse(fs.readFileSync(path.join(dir,id+'.json'),'utf8'))};},write(account,input,id,revision){if(account?.role!=='teacher'){const e=Error('교사만 맵을 만들 수 있습니다.');e.status=403;throw e;}const scene=normalizeScene(input);let entry;if(id){checkId(id);entry=find(id);if(!entry||entry.owner!==account.uid){const e=Error('내가 만든 맵만 편집할 수 있습니다.');e.status=403;throw e;}if(revision!==entry.revision){const e=Error('다른 창에서 수정되었습니다. 다시 열어 주세요.');e.status=409;throw e;}}else{if(entries.filter(e=>e.owner===account.uid).length>=30)throw Error('계정당 제작맵은 최대 30개입니다.');id='made-'+crypto.randomBytes(8).toString('hex');entry={id,owner:account.uid,author:account.name,revision:0};}
fs.mkdirSync(dir,{recursive:true,mode:0o700});for(const [ext,content]of [['json',JSON.stringify(scene)],['rbxlx',compileScene(scene,id,root)]]){const dest=path.join(dir,id+'.'+ext);fs.writeFileSync(dest+'.tmp',content,{mode:0o600});fs.renameSync(dest+'.tmp',dest);}Object.assign(entry,{title:scene.title,count:scene.objects.length,revision:entry.revision+1});if(!find(id))entries.push(entry);save();return {id,revision:entry.revision,scene};}};}
export function normalizeAppearance(input,base){const out={...base};for(const key of ['skin','torso','legs','hairColor','jacket']){if(!hex.test(input[key]||''))throw Error('색상 형식이 잘못됐습니다.');out[key]=input[key].toLowerCase();}if(!['swept','bun'].includes(input.hair))throw Error('지원하지 않는 헤어입니다.');out.hair=input.hair;out.custom=true;return out;}
