import * as THREE from 'three';import {OrbitControls}from'/robl/editor-assets/OrbitControls.js';
const $=s=>document.querySelector(s),base='/robl',status=$('#status');async function api(p,body){const r=await fetch(base+p,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const v=await r.json();if(!r.ok)throw Error(v.detail||'요청 실패');return v;}const act=fn=>async()=>{try{await fn()}catch(e){status.textContent=e.message;}};
let me,mode,appearance,initialAvatar,mapId=null,revision=null,selected=null,dragEnabled=false,dragging=null,lastPoint=new THREE.Vector3(),history=[],future=[];let data;let meshes=new Map();const world=new THREE.Scene();world.background=new THREE.Color('#c8ddeb');world.add(new THREE.HemisphereLight(0xffffff,0x5c6875,2.3));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(15,25,12);world.add(sun);const camera=new THREE.PerspectiveCamera(45,1,.1,2000);camera.position.set(42,38,48);let renderer;
try{renderer=new THREE.WebGLRenderer({antialias:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));$('#view').append(renderer.domElement);}catch(e){$('#loading').textContent='3D 미리보기를 열지 못했습니다: '+e.message;throw e;}
const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,2,0);controls.enableDamping=true;const grid=new THREE.GridHelper(128,64,0x4b7587,0x9eb5bc);world.add(grid);const content=new THREE.Group();world.add(content);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);let selectionBox;let dirty=false;
function resize(){const e=$('#view');renderer.setSize(e.clientWidth,e.clientHeight);camera.aspect=e.clientWidth/e.clientHeight;camera.updateProjectionMatrix();}new ResizeObserver(resize).observe($('#view'));
function dispose(){selectionBox?.removeFromParent();for(const child of [...content.children]){child.traverse(n=>{n.geometry?.dispose();if(n.material)for(const m of Array.isArray(n.material)?n.material:[n.material])m.dispose();});content.remove(child);}meshes.clear();}
function saveHistory(){history.push(JSON.stringify(data));if(history.length>60)history.shift();future=[];dirty=true;}
function newData(){return {version:1,title:'내가 만든 맵',objects:[{id:'floor',kind:'box',position:[0,-1,0],size:[64,2,64],rotation:[0,0,0],color:'#72a58e'},{id:'spawn',kind:'spawn',position:[0,1,0],size:[6,1,6],rotation:[0,0,0],color:'#94e8bb'}]};}
const textureCache=new Map();function texture(id){if(!textureCache.has(id)){const t=new THREE.TextureLoader().load(base+'/Asset/?id='+id);t.colorSpace=THREE.SRGBColorSpace;textureCache.set(id,t);}return textureCache.get(id);}
function meshFor(o){let g;if(o.kind==='ball')g=new THREE.SphereGeometry(.5,16,12);else if(o.kind==='cylinder'){g=new THREE.CylinderGeometry(.5,.5,1,16);g.rotateZ(Math.PI/2);}else if(o.kind==='wedge'){g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute([-.5,-.5,-.5,.5,-.5,-.5,.5,-.5,.5,-.5,-.5,.5,-.5,.5,.5,.5,.5,.5],3));g.setIndex([0,2,1,0,3,2,3,5,2,3,4,5,0,4,3,1,2,5,0,1,5,0,5,4]);g.computeVertexNormals();}else g=new THREE.BoxGeometry(1,1,1);const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:o.color,roughness:.85,map:o.texture?texture(o.texture):null}));m.position.fromArray(o.position);m.scale.fromArray(o.size);m.rotation.set(...o.rotation.map(n=>THREE.MathUtils.degToRad(n)));m.userData.id=o.id;return m;}
function renderMap(){dispose();grid.visible=true;for(const o of data.objects){const m=meshFor(o);meshes.set(o.id,m);content.add(m);}$('#objects').replaceChildren();for(const o of data.objects){const v=document.createElement('option');v.value=o.id;v.textContent=o.id+' · '+o.kind;$('#objects').append(v);}$('#title').value=data.title;select(selected);window.editorState={mode:'map',count:data.objects.length,id:mapId};}
function select(id){selected=data?.objects.find(o=>o.id===id)?.id||null;selectionBox?.removeFromParent();const o=data?.objects.find(o=>o.id===selected);$('#selected').textContent=o?o.id+' · '+o.kind:'부품을 선택해 주세요';for(const e of document.querySelectorAll('[data-prop]')){e.disabled=!o;e.value=o?o[e.dataset.prop][Number(e.dataset.axis)]:'';}$('#part-color').disabled=!o;$('#part-texture').disabled=!o;if(o){$('#part-texture').value=o.texture||'';$('#part-color').value=o.color;$('#objects').value=o.id;selectionBox=new THREE.BoxHelper(meshes.get(o.id),0xffc958);world.add(selectionBox);}}
function piece(group,kind,size,pos,color){const g=kind==='ball'?new THREE.SphereGeometry(.5,16,12):new THREE.BoxGeometry(1,1,1),m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.72}));m.scale.set(...size);m.position.set(...pos);group.add(m);return m;}
function renderAvatar(){dispose();grid.visible=false;camera.position.set(7,5,10);controls.target.set(0,2.6,0);const a=appearance;piece(content,'box',[1.8,1.9,1],[0,2.8,0],a.jacket);piece(content,'box',[.9,1.6,.06],[0,2.7,.55],a.hair==='bun'?'#dedbd5':a.torso);for(const s of[-1,1]){piece(content,'ball',[.7,1.6,.7],[s*1.35,2.7,0],a.skin);piece(content,'ball',[.78,.95,.8],[s*1.35,3.15,0],a.jacket);piece(content,'ball',[.45,.42,.35],[s*1.35,1.8,0],a.skin);piece(content,'box',[.75,1.7,.8],[s*.48,1.0,0],a.legs);piece(content,'ball',[.85,.48,1.15],[s*.48,.26,.15],'#202328');}piece(content,'ball',[1.3,1.12,1.1],[0,4.3,0],a.skin);piece(content,'ball',[1.39,.68,1.15],[0,4.8,-.04],a.hairColor);if(a.hair==='bun')piece(content,'ball',[.75,.75,.7],[.05,5.3,-.14],a.hairColor);else for(let i=0;i<6;i++)piece(content,'ball',[.25,.75,.3],[-.53+i*.21,4.7,.43],a.hairColor);
for(const s of[-1,1])piece(content,'ball',[.07,.1,.045],[s*.19,4.39,.55],'#222');for(let i=0;i<=8;i++){const t=Math.PI+i*Math.PI/8;piece(content,'ball',[.05,.05,.045],[Math.cos(t)*.24,4.15+Math.sin(t)*.17,.54],'#222');}window.editorState={mode:'avatar',hair:a.hair,parts:content.children.length};}
function setMode(value){mode=value==='map'&&me.role==='teacher'?'map':'avatar';$('#mode').value=mode;$('#map-panel').hidden=mode!=='map';$('#avatar-panel').hidden=mode!=='avatar';if(mode==='map'){camera.position.set(42,38,48);controls.target.set(0,2,0);renderMap();}else renderAvatar();}
function selectedObject(){return data.objects.find(o=>o.id===selected);}
for(const e of document.querySelectorAll('[data-prop]'))e.onchange=()=>{const o=selectedObject();if(!o)return;const n=Number(e.value);if(!Number.isFinite(n))return;saveHistory();o[e.dataset.prop][Number(e.dataset.axis)]=n;renderMap();};$('#part-color').onchange=()=>{if(!selectedObject())return;saveHistory();selectedObject().color=$('#part-color').value;renderMap();};$('#part-texture').onchange=()=>{if(!selectedObject())return;saveHistory();selectedObject().texture=$('#part-texture').value;renderMap();};$('#objects').onchange=()=>select($('#objects').value);
for(const e of document.querySelectorAll('[data-add]'))e.onclick=()=>{saveHistory();const kind=e.dataset.add,id='p-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);const obj={id,kind,position:[Math.round(lastPoint.x),kind==='spawn'?1:3,Math.round(lastPoint.z)],size:kind==='spawn'?[6,1,6]:[4,4,4],rotation:[0,0,0],color:kind==='spawn'?'#94e8bb':'#ddad6c'};data.objects.push(obj);selected=id;renderMap();};
$('#delete').onclick=()=>{if(!selectedObject())return;saveHistory();data.objects=data.objects.filter(o=>o.id!==selected);selected=null;renderMap();};$('#duplicate').onclick=()=>{const o=selectedObject();if(!o)return;saveHistory();const v=structuredClone(o);v.id='p-'+Date.now().toString(36);v.position[0]+=4;data.objects.push(v);selected=v.id;renderMap();};$('#undo').onclick=()=>{if(!history.length)return;future.push(JSON.stringify(data));data=JSON.parse(history.pop());renderMap();};$('#redo').onclick=()=>{if(!future.length)return;history.push(JSON.stringify(data));data=JSON.parse(future.pop());renderMap();};$('#drag').onclick=()=>{dragEnabled=!dragEnabled;$('#drag').textContent=dragEnabled?'이동 드래그 끄기':'이동 드래그 켜기';};
let down=null;function cast(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);}renderer.domElement.addEventListener('pointerdown',e=>{if(mode!=='map'||e.button!==0)return;cast(e);down={x:e.clientX,y:e.clientY};const hit=ray.intersectObjects([...meshes.values()])[0];if(hit){select(hit.object.userData.id);if(dragEnabled){saveHistory();controls.enabled=false;plane.constant=-selectedObject().position[1];const at=new THREE.Vector3();ray.ray.intersectPlane(plane,at);dragging={offset:new THREE.Vector3().fromArray(selectedObject().position).sub(at)};renderer.domElement.setPointerCapture(e.pointerId);}}else{plane.constant=0;ray.ray.intersectPlane(plane,lastPoint);}});renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;cast(e);const at=new THREE.Vector3();if(ray.ray.intersectPlane(plane,at)){at.add(dragging.offset);selectedObject().position=[Math.round(at.x),selectedObject().position[1],Math.round(at.z)];const m=meshes.get(selected);m.position.fromArray(selectedObject().position);selectionBox?.update();}});renderer.domElement.addEventListener('pointerup',()=>{if(dragging){dragging=null;controls.enabled=true;renderMap();}});
async function savedList(){const v=await api('/creator/maps');$('#saved').replaceChildren(new Option('맵 선택',''));for(const m of v.maps)if(m.editable)$('#saved').append(new Option(m.title,m.id));if(mapId)$('#saved').value=mapId;}
async function saveMap(){data.title=$('#title').value;const v=await api('/creator/map',{id:mapId,revision,scene:data});mapId=v.id;revision=v.revision;data=v.scene;dirty=false;await savedList();status.textContent='저장 완료 · 로블 맵 목록에 추가됐어요.';renderMap();return v;}
$('#save').onclick=act(saveMap);$('#apply').onclick=act(async()=>{await saveMap();if(!confirm('저장한 맵으로 변경합니다. 접속 중인 모두가 재입장해야 해요.'))return;await api('/maps/select',{id:mapId,forceRestart:true,confirmRestart:true});status.textContent='맵을 실행 중이에요. 로비로 돌아가서 준비 완료 후 입장해 주세요.';});$('#open').onclick=act(async()=>{const id=$('#saved').value;if(!id)return;const v=await api('/creator/map?id='+encodeURIComponent(id));data=v.scene;mapId=v.id;revision=v.revision;selected=null;history=[];future=[];renderMap();status.textContent='저장한 맵을 열었어요.';});$('#new').onclick=()=>{if(dirty&&!confirm('저장하지 않은 변경을 버리고 새 맵을 열까요?'))return;data=newData();mapId=null;revision=null;selected=null;history=[];renderMap();};$('#export').onclick=()=>{data.title=$('#title').value;const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='aiedue-robl-map.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);};$('#json-file').onchange=act(async()=>{const f=$('#json-file').files[0];if(!f||f.size>512000)throw Error('제작 파일은 512KB 이하입니다.');const v=JSON.parse(await f.text());if(!Array.isArray(v.objects)||v.objects.length>800)throw Error('부품 개수를 확인해 주세요.');data=v;mapId=null;revision=null;selected=null;renderMap();status.textContent='제작 파일을 열었어요. 저장할 때 서버에서 최종 검증합니다.';});$('#legacy-file').onchange=act(async()=>{const f=$('#legacy-file').files[0];if(!f||f.size>1048576)throw Error('구형 맵 파일은 1MB 이하만 지원합니다.');const bytes=new Uint8Array(await f.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));const v=await api('/creator/import',{data:btoa(text),title:f.name.replace(/\.rbxlx?(\.bz2)?$/i,'')});data=v.scene;mapId=null;revision=null;selected=null;renderMap();status.textContent=`지형 가져오기 완료 · 스크립트 ${v.report.scriptsRemoved}개 제외\n${v.report.notice}\n외부 에셋 참조 ${v.report.assetReferences.length}개는 별도 확인이 필요합니다.`;});
for(const e of document.querySelectorAll('[data-color]'))e.oninput=()=>{appearance[e.dataset.color]=e.value;renderAvatar();};$('#hair').onchange=()=>{appearance.hair=$('#hair').value;renderAvatar();};$('#avatar-save').onclick=act(async()=>{await api('/avatar/custom',appearance);status.textContent='내 캐릭터 저장 완료 · 다음 입장부터 적용돼요.';});$('#avatar-reset').onclick=act(async()=>{const v=await api('/avatar',{id:initialAvatar.id});appearance={...v.selected};fillAvatar();renderAvatar();status.textContent='기본 프리셋을 복원했어요.';});function fillAvatar(){for(const e of document.querySelectorAll('[data-color]'))e.value=appearance[e.dataset.color];$('#hair').value=appearance.hair;}$('#mode').onchange=()=>setMode($('#mode').value);
try{me=await api('/me');$('#who').textContent=me.name;const a=await api('/avatar');appearance={...a.selected};initialAvatar={...a.selected};fillAvatar();data=newData();if(me.role!=='teacher')$('#mode option[value=map]').remove();else await savedList();setMode(new URL(location.href).searchParams.get('mode'));const library=await api('/assets/library');$('#assets-info').textContent=library.protocols.join('\n')+'\n\n'+library.meshNotice+'\n\n'+library.references.map(r=>r.repo+': '+r.files+'개 목록 확인 · '+r.licenseNotice).join('\n');status.textContent=mode==='map'?'교사 맵 제작 준비 완료 · 시작점과 바닥을 포함해서 저장하세요.':'내 캐릭터 편집 준비 완료';$('#loading').remove();window.editorReady=true;}catch(e){status.textContent=e.message;$('#loading').textContent=e.message;}
function animate(){requestAnimationFrame(animate);controls.update();renderer.render(world,camera);}animate();window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
